services:
  # Backend API service
  - type: web
    name: audix-api
    env: node
    buildCommand: npm install --prefix backend
    startCommand: npm run start --prefix backend
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: CLERK_PUBLISHABLE_KEY
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: ADMIN_EMAIL
        sync: false

  # Frontend service
  - type: web
    name: audix-web
    env: node
    buildCommand: npm install --prefix frontend && npm run build --prefix frontend
    startCommand: cd frontend && npx serve -s dist
    envVars:
      - key: VITE_CLERK_PUBLISHABLE_KEY
        sync: false
      - key: VITE_API_URL
        value: https://audix-api.onrender.com/api
