services:
  # Backend API service
  - type: web
    name: audix-api
    env: node
    plan: free
    repo: https://github.com/iamsalvin/Audix-Realtime_SpotifyClone.git
    branch: master
    root: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/health

  # Frontend app as a static site
  - type: web
    name: audix-frontend
    env: static
    buildCommand: cd ../frontend && npm install && npm run build
    staticPublishPath: ../frontend/dist
    repo: https://github.com/iamsalvin/Audix-Realtime_SpotifyClone.git
    branch: master
    root: backend # We use backend as root but build from frontend dir
    envVars:
      - key: NODE_ENV
        value: production
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
